apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1 # number of pods to run for each image
  selector: # the selector will look for all pods that were created and match the label with app label - posts-service
    matchLabels:
      app: client
  template: # the template we specify the configuration to the deployment that we are going to make
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: yazanalmatar99/client:latest # latest refers to the latest version
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector:
    app: client
  # type: ClusterIP
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
