apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-service-depl
spec:
  replicas: 1 # number of pods to run for each image
  selector: # the selector will look for all pods that were created and match the label with app label - event-bus
    matchLabels:
      app: moderation-service
  template: # the template we specify the configuration to the deployment that we are going to make
    metadata:
      labels:
        app: moderation-service
    spec:
      containers:
        - name: moderation-service
          image: yazanalmatar99/moderation-service:latest # latest refers to the latest version
---
apiVersion: v1
kind: Service
metadata:
  name: moderation-srv
spec:
  selector:
    app: moderation-service
  # type: ClusterIP
  ports:
    - name: moderation-service
      protocol: TCP
      port: 4003
      targetPort: 4003
